### ISSUE TITLE
Invoking SSS on select multiple doesn't hide the select

### ISSUE THREAD

**Issue by rouilj** [chalda-pnuzig/SimpleSearchableSelect#1]
I have been looking for a replacement for Select 2 and this looks promising.
However when I invoke SSS on the select multiple element, I do get the separate inputs, and
the select is updated. But the select isn't hidden as shown in the screenshot. Any ideas?

**Comment by rouilj** [comment]
Ok, finally got the image to upload.

<img width="382" alt="SSS_not_hiding_select" src="https://github.com/chalda-pnuzig/SimpleSearchableSelect/assets/3751752/0612d884-0fdb-473d-9d4c-5d520b844594">

**Comment by chalda-pnuzig** [comment]
Hello,
The 'select' is hidden using the standard HTML `hidden` attribute.
Perhaps in your CSS, there's a rule that makes it visible?

It's possible that some CSS libraries may override this rule. However, you can address the issue with this simple CSS rule:

```css
[hidden] {
    display: none!important;
}
```

**Comment by rouilj** [comment]
Thanks for the pointer. I had a 'display: inline-block' on the select that was making it visible.
Once I changed the CSS rule to apply only if `:not([hidden])` the pesky select went away.

I may be back with a few more questions. I still have an issue where the active input box doesn't show a placeholder/prompt. I assume the placeholder is identified by the option with an empty value (value="")?

I am also trying to format the selected items inside a wrapping flexbox to make them more compact.
Obviously, this compact form will only apply to desktop or other devices where swipe gestures won't be used.

Thanks for your help.

**Comment by chalda-pnuzig** [comment]
> I may be back with a few more questions. I still have an issue where the active input box doesn't show a placeholder/prompt. I assume the placeholder is identified by the option with an empty value (value="")?

Yes, however, I added the option to be able to specify it in version 1.1.0

**Comment by rouilj** [comment]
> Yes, however, I added the option to be able to specify it in version 1.1.0

Thanks. I had an issue with select multiple when clearing all the selected items and submitting
the form, the empty select multiple wasn't sent IIRC. So there is an explicit select option with '-1' value to force a submit and clear all the rest of the items.

The `<option value="-1">Select a keyword</option>` wasn't identified as the placeholder/default text.
