### ISSUE TITLE
Not working on android with firefox??

### ISSUE THREAD

**Issue by rouilj** [chalda-pnuzig/SimpleSearchableSelect#3]
I tried going to your test page:

  https://chalda-pnuzig.github.io/SimpleSearchableSelect/demo/

on an android device. When I used chrome in an enhanced multiselect, my matches were displayed in a
horizontally scrolling line of pills along the bottom of the page and I could select it by clicking.

When I did the same with firefox, there was nothing displaying the matches. Any ideas?

**Comment by rouilj** [comment]
Apparently a known bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1535985

**Comment by chalda-pnuzig** [comment]
On firefox if I click on the input and then click it again the datalist appears:

![image](https://github.com/chalda-pnuzig/SimpleSearchableSelect/assets/16133710/e5dd6f66-5d0d-4ee7-bbdc-c20ad49c0219)

**Comment by rouilj** [comment]
My issue was on android mobile. It looks like your example is desktop.
